---
# Here we describe software we want to install
- hosts: all
  tasks: 
    - name: Tap homebrew repositories
      homebrew_tap: name={{ item }} state=present
      with_items:
        - caskroom/cask

    - name: Install software with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - git
        - go
        - tintin
        - tmux
        - cmake
        - curl
        - python
        - tree
        - wget
        - cloc
        - the_silver_searcher
        - brew-cask

    - name: Install VIM and override system VIM
      homebrew: name=vim state=present install_options=override-system-vi

    - name: Install software with homebrew cask
      homebrew_cask: name={{ item }} state=present
      with_items:
        - iterm2
        -  hipchat
        -  google-chrome
        -  alfred
        -  sublime-text
        -  dropbox
        -  1password
        -  citrix-receiver
        -  transmission
        -  vlc
        -  openemu
        -  keepingyouawake
        -  java
        -  steam
        -  spotify
        -  calibre
        -  licecap
        -  quicklook-csv
        -  quicklook-json

    - name: Check if Oh My Zsh is already installed
      stat: path=~/.oh-my-zsh
      register: zsh

    - name: Install Oh My Zsh
      command: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      when: zsh.stat.exists == False
